site_name: OpticalRS

repo_url: https://github.com/jkibele/OpticalRS

site_author: Jared Kibele

pages:
- Home: index.md
- Installation: installation.md
- User Guide: userguide.md
- Modules: modules.md

theme: bootstrap

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True
